import type { Brand } from '../types/brand.js'

/**
 * Branded type for a user identifier.
 *
 * Why: Using a brand prevents accidental mixing of plain strings with
 * validated UserId values at the type level, with zero runtime overhead.
 */
export type UserId = Brand<string, 'UserId'>

/**
 * Wraps a string as a UserId branded type without additional validation.
 *
 * Why: UserIds are generated by the infrastructure layer (e.g., crypto.randomUUID).
 * The domain trusts them as-is but brands them so they cannot be confused with
 * arbitrary strings at compile time.
 *
 * @param value - The raw string value to brand as UserId.
 * @returns A branded UserId value.
 */
export const createUserId = (value: string): UserId => value as UserId
